# Profile information
name: Alex's Music Club
title: Alex's Music CLub
description: > # this means to ignore newlines until "baseurl:"
  A music-sharing website based on the jekyll theme "fresh". Found by Jiawei Chen.
  基于Jekyll的音乐分享网站，由陈嘉纬创建于2021.

permalink: ':title/'
#baseurl: "/fresh" # the subpath of your site, e.g. /blog
baseurl: ""
url: "artemsheludko.pw" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github: AlexJWC
bilibili: LINKJW
QQ: 3087534304
twitter: LINKJW4

# Contact form
email: 13336039319@163.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
